### ISSUE TITLE
사용자가 어떻게 사용해볼 수 있나요? 

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-spring-4-sejongdeveloper#29]
사용자가 사용할 수 있어야 비로소 가치가 전달됩니다. 사용해볼 수 있었으면 좋겠습니다.

**Comment by sejongdeveloper** [comment]
발주 기능이 완료하고 나서 사용자가 이용할 수 있는 간단한 페이지를 만들겠습니다.
